"""An HTTP client for a Ridal server.

Needs the ``client`` extra: ``pip install ridal[client]``.

>>> import ridal.client  # doctest: +SKIP
>>> with ridal.client.Client("https://ridal.example.org", project="glac") as client:  # doctest: +SKIP
...     print(client.health().version)
"""

from ridal.client._client import DEFAULT_PROJECT, TOKEN_VARIABLE, Client
from ridal.client.errors import (
    BadRequest,
    Conflict,
    Forbidden,
    NotAProject,
    NotFound,
    PayloadTooLarge,
    PreconditionFailed,
    ProtocolError,
    ReplacementRefused,
    RidalError,
    ServerError,
    TransportError,
    Unauthorized,
    Unavailable,
)
from ridal.client.models import (
    Added,
    Axes,
    CarriedView,
    CarryReport,
    Catalog,
    ConsequenceReport,
    Dataset,
    Displacement,
    Document,
    DocumentConsequence,
    Dropped,
    FeatureCollection,
    Grant,
    Health,
    Interpretation,
    InterpretationList,
    Me,
    Project,
    Promoted,
    Replaced,
    Saved,
    ShapeChange,
    SignedIn,
    Staged,
    TokenSummary,
)
from ridal.client.plan import Outcome, Plan, Record
from ridal.client.progress import Progress, ProgressEvent, tqdm_progress

__all__ = [
    "DEFAULT_PROJECT",
    "TOKEN_VARIABLE",
    "Added",
    "Axes",
    "BadRequest",
    "CarriedView",
    "CarryReport",
    "Catalog",
    "Client",
    "Conflict",
    "ConsequenceReport",
    "Dataset",
    "Displacement",
    "Document",
    "DocumentConsequence",
    "Dropped",
    "FeatureCollection",
    "Forbidden",
    "Grant",
    "Health",
    "Interpretation",
    "InterpretationList",
    "Me",
    "NotAProject",
    "NotFound",
    "Outcome",
    "PayloadTooLarge",
    "Plan",
    "PreconditionFailed",
    "Progress",
    "ProgressEvent",
    "Project",
    "Promoted",
    "ProtocolError",
    "Record",
    "Replaced",
    "ReplacementRefused",
    "RidalError",
    "Saved",
    "ServerError",
    "ShapeChange",
    "SignedIn",
    "Staged",
    "TokenSummary",
    "TransportError",
    "Unauthorized",
    "Unavailable",
    "tqdm_progress",
]
